### PR TITLE
OPS-158: Boostrap CI

### PR DESCRIPTION
**Pull request by enys**

### CODE REVIEW

**Comment by enys** [comment]
This will result in the upload of : linkurious-lke-plugin-data-table-1.0.3-OPS-158.4.lke

We need to discuss plugin names

**Comment by enys** [comment]
We need a proper .eslintrc.js file too

**Comment by davidrapin** [comment]
the plugin name has no impact, the name used by LKE is from the internal manifest.

**Comment by enys** [comment]
@davidrapin  thx. Have updated name to match our discussion

**Pull request merged**
